CREATE DATABASE exercise1;
CREATE TABLE EMP_1(`EMP_NUM` CHAR(3) NOT NULL, `EMP_Lname` VARCHAR(15) NULL, `EMP_FNAME` VARCHAR(15) NULL, `EMP_INITIAL` VARCHAR(1) NULL, `EMP_HIREDATE` DATE NULL, `JOB_CODE` CHAR(3) NULL);
SELECT *FROM EMP_1;
INSERT INTO EMP_1(EMP_NUM, EMP_Lname, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
VALUES('1','Goce', 'Denise', 'T', '2023-03-27', '501');
INSERT INTO EMP_1(EMP_NUM, EMP_Lname, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
VALUES('2','Isidro', 'Kasandra', 'A', '2023-03-21', '502');
SELECT *FROM EMP_1
WHERE JOB_CODE= '502';